import { resolve } from 'path';
import { existsSync, readdirSync } from 'fs';
import { getProjectRoot, log, logSuccess, logError, logStep, runCommand, runWithRetry, sleep } from '../utils';

export async function initCommand(): Promise<void> {
  const root = getProjectRoot();
  const totalSteps = 4;

  log('Initializing MemPalace Explorer...\n');

  try {
    logStep(1, totalSteps, 'Installing dependencies...');
    await runCommand('npm', ['install'], { cwd: root });
    logSuccess('Dependencies installed.\n');

    logStep(2, totalSteps, 'Generating Prisma client...');
    const clientIndex = resolve(root, 'node_modules', '.prisma', 'client', 'index.js');
    const prismaClientDir = resolve(root, 'node_modules', '.prisma', 'client');
    const hasEngineFile = existsSync(prismaClientDir) && 
      readdirSync(prismaClientDir).some((f: string) => f.includes('query_engine'));
    if (hasEngineFile && existsSync(clientIndex)) {
      logSuccess('Prisma client already generated by npm install.\n');
    } else {
      await sleep(2000);
      await runWithRetry('npx', ['prisma', 'generate', '--schema=server/prisma/schema.prisma'], { cwd: root });
      logSuccess('Prisma client generated.\n');
    }

    logStep(3, totalSteps, 'Running database migrations...');
    await runCommand('npx', ['prisma', 'migrate', 'deploy', '--schema=server/prisma/schema.prisma'], { cwd: root });
    logSuccess('Database ready.\n');

    logStep(4, totalSteps, 'Building client and server...');
    await runCommand('npm', ['run', 'build'], { cwd: root });
    logSuccess('Build complete.\n');

    console.log('');
    logSuccess('MemPalace Explorer is ready!');
    log('Run \x1b[1mmempalace-explorer run\x1b[0m to start the application.');
    log('Run \x1b[1mmempalace-explorer run --dev\x1b[0m for development mode with HMR.');
    console.log('');
  } catch (err: any) {
    logError(`Initialization failed: ${err.message}`);
    process.exit(1);
  }
}
